const PRODUCTS_CATEGORY = [
  {
    category: "electrics",
    children: [
      {
        name: "Reflectores LED",
        listProducts: [
          "50 Watts",
          "100 watts",
          "200 watts",
          "300 watts",
          "400 watts",
          "500 watts",
        ],
      },
      {
        name: "Lámparas y focos LED",
        listProducts: [
          "3 Watts",
          "7 watts",
          "9 watts",
          "12 watts",
          "15 watts",
          "20 watts",
          "30 watts",
          "40 watts",
          "50 watts",
          "60 watts",
          "70 watts",
        ],
      },
      {
        name: "Alumbrado Público",
        listProducts: [
          "30 watts",
          "60 watts",
          "80 watts",
          "100 watts",
          "120 watts",
          "150 watts",
          "180 watts",
          "200 watts",
        ],
      },
      {
        name: "Abrazaderas para pastorales",
        listProducts: ["Simple", "Doble", "Triple", "Unifix"],
      },
      {
        name: "Soldadura Exótérmica",
        listProducts: ["Tenaza", "Chispero", "Masillas", "Cepillos"],
      },
      {
        name: "Pararrayos Polimérico",
        listProducts: [
          "18Kv a 10Kv",
          "21Kv a 10Kv",
          "24Kv a 10Kv",
          "27Kv a 10Kv",
          "36Kv a 10Kv",
          "De Distribución",
          "De Estación",
          "De Línea",
        ],
      },
      {
        name: "Pastorales",
        listProducts: ["Tipo parabólico", "Simple largo", "Simple corto"],
      },
      {
        name: "Pararrayos Tetrapuntual",
        listProducts: [
          "Pararrayos Tetrapuntual Tipo Franklin",
          "Thor Tetrapuntual Tipo Franklin",
        ],
      },
      {
        name: "Abrazaderas de soporte para Tubería",
        listProducts: [
          "Doble Ala",
          "Perpendicular Ajustable",
          "Caja de Empalme 12x12x5",
          "Grapa 'U'",
          "Soporte Cuelga",
        ],
      },
      {
        name: "Caja de Registro",
        listProducts: [
          "Concreto Cuadrada",
          "Concreto Redondo",
          "Polipropileno",
        ],
      },
      {
        name: "Materiales",
        listProducts: [
          "Bentonita Sódica",
          "Disagel",
          "Erico Gem 25A",
          "Favigel",
          "Redugel",
          "Sal Industrial",
          "San Earth",
          "Thor Cem",
          "Thor Gel",
          "Tierra Gel",
        ],
      },
      {
        name: "Accesorios",
        listProducts: [
          "Split Bold",
          "Conector Tipo G",
          "Grapas",
          "Conector AB",
          "Tribarra Repotenciada",
          "Varillas de Cobre",
          "Varillas de Copperweld",
          "De Línea",
        ],
      },
      {
        name: "Tableros Metálicos",
        listProducts: [
          "Tableros Adosados",
          "Tableros Empotrados",
          "Tableros Autosoportados",
        ],
      },
      {
        name: "Tableros PVC",
        listProducts: ["Tableros Adosados", "Tableros Empotrados"],
      },
      {
        name: "Manguera Corrugada",
        listProducts: [
          "Para Ámbito Informático",
          "Para Identificar una Emergencia",
          "Para Cableado de Sonido",
          "Para Electricidad Domiciliaria",
          "Para Telefonía",
          "Para Video Portero",
        ],
      },
      {
        name: "Cintas Aislantes y vulcanizadas",
        listProducts: [
          "Cinta Aislante Indeco",
          "Cinta Aislante 3M",
          "Cinta Aislante Truper",
          "Cinta Aislante Pretrul",
          "Cinta Vulcanizada 3M",
          "Cinta Autosoldable Tacsa",
        ],
      },
      {
        name: "Cajas de pase PVC I",
        listProducts: [
          "Caja Estanca",
          "Caja Rectangular",
          "Caja Octogonal",
          "Caja Redonda",
        ],
      },
      {
        name: "Cajas de pase PVC II",
        listProducts: [
          "Caja Condulet Tipo C",
          "Caja Condulet Tipo LR",
          "Caja Condulet Tipo T",
          "Caja Condulet Tipo LB",
          "Caja Condulet Tipo LL",
        ],
      },
      {
        name: "Tapas ciegas PVC",
        listProducts: [
          "Tapa Rectangular",
          "Tapa Redonda",
          "Tapa Octogonal",
          "Tapa Flux Suplemento",
          "Canaletas Pasacables",
        ],
      },
      {
        name: "Accesorios PVC",
        listProducts: [
          'Curva Sel x 5/8" -3/4" -1" -1(1/4)"-1(1/2)"-2"',
          'Conector Sel x 5/8" -3/4" -1" -1(1/4)"-1(1/2)"-2"',
          'Union Sel x 5/8" -3/4" -1" -1(1/4)"-1(1/2)"-2"',
          "Prensaestopa",
          "Cinltillos",
          "Tubos Conduit",
          "Grapas",
        ],
      },
      {
        name: "Accesorios de Metal",
        listProducts: [
          "Tubos Conduits",
          "Abrazaderas Simples",
          "Abrazaderas Caddy Tipo O",
          "Curvas Conduits",
          "Unión Emt",
          "Bandeja Portacable Perforada",
          "Tubo Bastón Para Acometidas",
          "Conector Metálico Recto",
        ],
      },
      {
        name: "Terminales",
        listProducts: [
          "Terminal Plano",
          "Terminal Hembra",
          "Terminal Redondo",
          "Terminal Horquilla",
          "Terminal Punta Tubular",
          "Terminal Tipo Pin Cobre Estaño",
          "Terminal de Compresión",
          "Terminal 90° Doble Agujero",
          "Terminal Tipo Lengüeta",
        ],
      },
      {
        name: "Tomacorriente y Enchufes industriales",
        listProducts: [
          "Enchufe 16A 2P+T 250V",
          "Enchufe 32A 3P+T 380 A 415V",
          "Enchufe 63A 3P+T 380 A 415V",
          "Enchufe Schuko 16A 2P+T 250V",
          "Toma Visible 16A 2P+T 200 A 250A",
          "Toma Visible 32A 3P+T 380 A 415V",
          "Toma Aéreo 32A 3P+T 380 A 415A",
          "Toma Aéreo 63A 3P+T 380 A 415",
          "Toma Visible Schuko 16A 2P+T 250V",
          "Toma Empotrable Schuko 16A 2P+T 250V",
          "Toma Empotrable 32A 3P+T 380 A 415V",
          "Toma Empotrable 63A 3P+T 415V",
          "Delta-Box 16A 2P+T (Pulpo)",
          "Delta-Box 32A 2P+T (Pulpo)",
        ],
      },
    ],
  },
];
